# Generated by Django 5.1.7 on 2025-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_chat_content_alter_room_character_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="fixation",
            field=models.BooleanField(default=False),
        ),
    ]
