# Generated by Django 5.1.7 on 2025-07-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_chat_content_alter_room_character_id_and_more"),
        ("rooms", "0002_alter_room_character_id"),
    ]

    operations = []
