# Generated by Django 5.1.7 on 2025-07-01 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0008_merge_20250629_1545"),
        ("rooms", "0003_merge_20250701_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="character_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="characters.character",
            ),
        ),
    ]
