# Generated by Django 5.1.7 on 2025-07-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room_fixation"),
        ("rooms", "0004_alter_room_character_id"),
    ]

    operations = []
