# Generated by Django 5.1.7 on 2025-07-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_rename_character_id_room_character_alter_room_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="character",
        ),
    ]
