# Generated by Django 5.1.7 on 2025-07-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_rename_character_id_room_character_alter_room_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="room_id",
            new_name="uuid",
        ),
    ]
