# Generated by Django 5.1.7 on 2025-07-02 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_rename_room_id_room_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="chat_id",
            new_name="id",
        ),
    ]
