# Generated by Django 5.1.7 on 2025-07-03 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0012_rename_character_uuid_character_character_id_and_more"),
        ("rooms", "0007_remove_room_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="character",
            field=models.ForeignKey(
                default="f47ac10b-58cc-4372-a567-0e02b2c3d479",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="characters.character",
            ),
            preserve_default=False,
        ),
    ]
