# Generated by Django 5.1.7 on 2025-07-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_rename_chat_id_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_main",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="regeneration_group",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
