# Generated by Django 5.1.7 on 2025-07-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_room_character"),
        ("rooms", "0009_chat_is_main_chat_regeneration_group"),
    ]

    operations = []
