# Generated by Django 5.1.7 on 2025-07-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0010_merge_20250703_1555"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="user",
        ),
    ]
