services:
  django_app:
    build:
      context: .
    container_name: beta_django_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app_network
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn beta.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: beta_nginx
    depends_on:
      - django_app
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
      - media_volume:/media

  pgadmin:
    image: dpage/pgadmin4
    container_name: beta_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    ports:
      - "8080:80"
    networks:
      - app_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  app_network:
    driver: bridge

volumes:
  pgadmin_data:
  static_volume:
  media_volume: