# Generated by Django 5.1.7 on 2025-06-11 05:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("chat_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(verbose_name="메시지 내용")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("ai", "AI")],
                        max_length=10,
                        verbose_name="역할",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성시간"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "verbose_name_plural": "채팅 메시지들",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "character_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="챗봇 ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="채팅방 제목")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="생성시간"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정시간"),
                ),
            ],
            options={
                "verbose_name": "채팅방",
                "verbose_name_plural": "채팅방들",
            },
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.AddField(
            model_name="chat",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="room.room",
                verbose_name="채팅방",
            ),
        ),
    ]
