# Generated by Django 5.1.7 on 2025-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_room_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="character_id",
            field=models.CharField(max_length=50, verbose_name="챗봇 ID"),
        ),
    ]
