# Generated by Django 5.1.7 on 2025-06-19 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_alter_room_character_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="uuid_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
