# Generated by Django 5.1.7 on 2025-06-19 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0005_room_uuid_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="room",
        ),
        migrations.RemoveField(
            model_name="room",
            name="user",
        ),
        migrations.AlterField(
            model_name="room",
            name="room_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="room",
            name="uuid_id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
