# Generated by Django 5.1.7 on 2025-06-19 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0006_remove_chat_room_remove_room_user_alter_room_room_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="room_id",
        ),
        migrations.AddField(
            model_name="chat",
            name="room",
            field=models.ForeignKey(
                default=uuid.UUID("d810eba6-9f18-4f49-8a40-082066e33eca"),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="room.room",
                verbose_name="채팅방",
            ),
            preserve_default=False,
        ),
    ]
