# Generated by Django 5.1.7 on 2025-06-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0007_remove_room_room_id_chat_room"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="uuid_id",
            new_name="room_id",
        ),
    ]
