# Generated by Django 5.1.7 on 2025-06-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0010_alter_room_character_id_alter_room_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="title",
        ),
    ]
