# Generated by Django 5.1.7 on 2025-06-14 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                ("character", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                (
                    "character_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="character/image/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("intro", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("character_info", models.TextField(blank=True, null=True)),
                ("example_situation", models.TextField(blank=True, null=True)),
                ("presentation", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
