# Generated by Django 5.1.7 on 2025-06-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="creator_comment",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="is_character_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="character",
            name="is_description_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="character",
            name="is_example_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="character",
            name="presentation",
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="title",
            field=models.CharField(max_length=20),
        ),
    ]
