# Generated by Django 5.1.7 on 2025-06-22 01:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_character_creator_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="example_situation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="intro",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250), default=list, size=None
            ),
        ),
    ]
