# Generated by Django 5.1.7 on 2025-06-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_alter_character_example_situation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="example_situation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="intro",
            field=models.TextField(),
        ),
    ]
