# Generated by Django 5.1.7 on 2025-06-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_alter_character_example_situation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="example_situation",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="intro",
            field=models.JSONField(default=list),
        ),
    ]
