# Generated by Django 5.1.7 on 2025-06-24 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_alter_character_example_situation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="scrapped_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="scrapped_characters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
