# Generated by Django 5.1.7 on 2025-06-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_scrapped_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='tag_characters', to='characters.hashtag'),
        ),
    ]
