# Generated by Django 5.1.7 on 2025-06-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0007_conversationhistory"),
        ("characters", "0007_hashtag_character_hashtags"),
    ]

    operations = []
