# Generated by Django 5.1.7 on 2025-07-01 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0008_merge_20250629_1545"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="character",
            new_name="character_id",
        ),
        migrations.AlterField(
            model_name="character",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="characters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
