# Generated by Django 5.1.7 on 2025-07-03 05:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0009_rename_character_character_character_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="hashtags",
        ),
        migrations.RemoveField(
            model_name="character",
            name="scrapped_by",
        ),
        migrations.RemoveField(
            model_name="conversationhistory",
            name="character",
        ),
        migrations.AddField(
            model_name="character",
            name="character_uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
