# Generated by Django 5.1.7 on 2025-07-03 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0010_remove_character_hashtags_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="character_id",
        ),
        migrations.AlterField(
            model_name="character",
            name="character_uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
