# Generated by Django 5.1.7 on 2025-07-03 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0011_remove_character_character_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="character",
            old_name="character_uuid",
            new_name="character_id",
        ),
        migrations.AddField(
            model_name="character",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="tag_characters", to="characters.hashtag"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="scrapped_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="scrapped_characters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversationhistory",
            name="character",
            field=models.ForeignKey(
                default="f47ac10b-58cc-4372-a567-0e02b2c3d479",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation_histories",
                to="characters.character",
            ),
            preserve_default=False,
        ),
    ]
