# Generated by Django 5.1.7 on 2025-07-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0012_rename_character_uuid_character_character_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="user",
        ),
        migrations.RemoveField(
            model_name="conversationhistory",
            name="user",
        ),
    ]
