# Generated by Django 5.1.7 on 2025-06-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "남자"), ("F", "여자"), ("O", "기타")],
                default="O",
                max_length=1,
            ),
        ),
    ]
