# Generated by Django 5.1.7 on 2025-06-11 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_deactivated_at_user_is_deactivated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deactivated_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_deactivated",
        ),
    ]
