# Generated by Django 5.1.7 on 2025-06-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_email"),
        ("accounts", "0006_remove_user_deactivated_at_and_more"),
    ]

    operations = []
