# Generated by Django 5.1.7 on 2025-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
