# Generated by Django 5.1.7 on 2025-06-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_profile_picture_alter_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="introduce",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
