# Generated by Django 5.1.7 on 2025-06-26 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_chatprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatprofile",
            name="chatprofile_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
