# Generated by Django 5.1.7 on 2025-07-03 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_user_deactivated_at_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_nickname", models.CharField(max_length=30)),
                (
                    "chat_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "chat_profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="chat_profiles/"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
