# Generated by Django 5.1.7 on 2025-07-04 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_chatprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatprofile",
            name="id",
        ),
        migrations.AddField(
            model_name="chatprofile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
