# Generated by Django 5.1.7 on 2025-07-06 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_chatprofile_id_chatprofile_uuid"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="chatprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RemoveField(
            model_name="follow",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="to_user",
        ),
    ]
