# Generated by Django 5.1.7 on 2025-07-06 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_user_id_alter_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatprofile",
            name="user",
            field=models.ForeignKey(
                default="6dc91401-2e09-49b1-ab8e-01b8eff9651c",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="follow",
            name="from_user",
            field=models.ForeignKey(
                default="5a7f26b1-4f61-48e3-8f25-1c0ddc0a4ad7",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="follow",
            name="to_user",
            field=models.ForeignKey(
                default="5a7f26b1-4f61-48e3-8f25-1c0ddc0a4ad7",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("from_user", "to_user")},
        ),
    ]
